name: decks
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.0
      with:
        node-version: '12'

    - name: Install Dependencies
      run: yarn install
    - name: Build Dependencies
      run: yarn build
    - name: Build Site
      run: yarn workspace @lefthoek/decks build
    - name: Deploy Site
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      uses: reggionick/s3-deploy@v1
      with:
        folder: sites/decks/public
        bucket: ${{ secrets.DECKS_BUCKET }}
        dist-id: ${{ secrets.DECKS_DISTRIBUTION_ID }}
